import 'package:firebase_analytics/firebase_analytics.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:proj_08_feliciatan/bmi_calc.dart';
import 'package:proj_08_feliciatan/login.dart';
import 'firebase_options.dart'; // Generated by Firebase CLI (covered below)
import 'package:firebase_storage/firebase_storage.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:firebase_auth/firebase_auth.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase based on platform
  await Firebase.initializeApp(
    options: kIsWeb
        ? FirebaseOptions(
      apiKey: "AIzaSyAfGpX4qd8rmP6stl6uAiPHcQ6H9yvXOpI",
      authDomain: "proj-08-feliciatan.firebaseapp.com",
      projectId: "proj-08-feliciatan",
      storageBucket: "proj-08-feliciatan.appspot.com",
      messagingSenderId: "207291588069",
      appId: "1:207291588069:web:e689cb0aebacc6760e630c",
      measurementId: "G-58N5HNLSYD",
      databaseURL: "https://proj-08-feliciatan-default-rtdb.asia-southeast1.firebasedatabase.app", // Correct Realtime Database URL
    )
        : DefaultFirebaseOptions.currentPlatform, // For other platforms like Android/iOS
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  static FirebaseAnalytics analytics = FirebaseAnalytics.instance;
  //FirebaseAnalytics.instance returns the singleton instance of FirebaseAnalytics, which is used to log events and gather analytics data.
  //The static keyword means that analytics can be accessed directly through the class without needing an instance of the class.
  static FirebaseAnalyticsObserver observer = FirebaseAnalyticsObserver(analytics: analytics);
  //FirebaseAnalyticsObserver is an observer class that listens for navigation events in your app and automatically logs page view events to Firebase Analytics.
  //By passing the analytics instance to the observer, it ties the observer to the specific Firebase Analytics instance you initialized earlier.
  //This observer can be used in the MaterialApp or CupertinoApp to monitor navigation changes.

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      navigatorObservers: <NavigatorObserver>[observer], // Add observer here
      debugShowCheckedModeBanner: false,
      title: 'Clowner Food Blog',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const LoginPage(), // Start at LoginPage
    );
  }
}

